name: CI

on: [push]

env:
  APP_BUNDLE_NAME: "App"
  APP_BUNDLE_PATH: "./build"
  ARCHIVE_NAME: "Archive"
  ARCHIVE_PATH: "./Archive.xcarchive"
  CONFIGURATION: "Release"
  SCHEME: "Blink"

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: get frameworks
      run: ./get_frameworks.sh
    - name: yarn
      run: cd KB/JS && yarn
    - name: yarn test
      run: cd KB/JS && yarn test
    - name: Build archive
      run: |
        set -o pipefail && xcodebuild -project Blink.xcodeproj -scheme $SCHEME -sdk iphoneos -configuration $CONFIGURATION archive -archivePath $ARCHIVE_PATH CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO
    - name: Export ipa
      run: |
        set -o pipefail && xcodebuild -exportArchive -archivePath $ARCHIVE_NAME -exportOptionsPlist ./devops/exportOptions.plist -exportPath $APP_BUNDLE_PATH
    - name: Upload ipa
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.APP_BUNDLE_NAME }}
        path: ${{ env.APP_BUNDLE_PATH }}
